### ISSUE TITLE
Add metrics for performance visibility

### ISSUE THREAD

**Issue by velvia** [filodb/FiloDB#106]
## High Level

- Memory free

### Spark

- time spent reading/writing table metadata (eg schemas), vs
- time spent on actual ingestion

For streaming jobs where each data frame write is small, the first item could be very significant, and we might need to cache metadata.

### Per Dataset

- time spent converting to binary chunks for segment writes
- time spent writing to memtable
- time spent waiting / unable to write to memtable because it's full (means waiting for flush)
    - If this is high, that means either memory is low or flush is slower than rate of data ingest

## ColumnStore stats

- # of unlogged batches / batches of columnar chunks written
- Histogram of size in bytes of each batch of columnar chunks (each call to writeChunks()), and number of chunks
- Histogram of size in bytes of chunkRowMaps (indexes) written
- cache hits vs misses for writes
- time spent for entire appendSegment, for reads back from cache misses, for individual writes of each type

**Comment by velvia** [comment]
@parekuti @venugopalrp if you guys have anything to add to the above list, please feel free.  They are metrics that should help debug ingestion.

**Comment by parekuti** [comment]
- Add feature to get ingestion stats per table instead of writing to the log file.
- Number of write requests that are failed during ingestion.
- Max/Min partition size per each chunk and chunRowMap table

**Comment by velvia** [comment]
@parekuti 

* ingestion stats per table - this is already available via API (`FiloDriver.client.ingestionStats(ref, 0)` for example - see StreamingStress.scala), and will be added to the metrics framework
* # write requests that failed - good idea, will add these.  Note that though right now any reprojection failure will stop the ingestion.
* Partition size stats are already available from Cassandra - I think you can do node tool cfstats .
We will be adding some stats though for ingestion chunk size.

**Comment by velvia** [comment]
Closing this.  Kamon stats have been merged to master.
