### ISSUE TITLE
Provide data eviction functionality

### ISSUE THREAD

**Issue by ccackerman** [filodb/FiloDB#112]
When dynamic datasets such as streaming data are ingested into FiloDB, the need arises to evict data that is no longer of interest. 
Currently it is an option to write to different tables over time and delete obsolete tables with Cassandra or filo-cli, but this complicates queries.
A more elegant eviction mechanism is preferable.
It may be noted that eviction will be required on an ongoing basis and should be efficient enough to match the ingestion rate without adding too much overhead.
### Proposal

Two proposed avenues of data eviction for FiloDB (from Evan):
1. The easiest is definitely to set a TTL.   This can be enabled very easily, through some option in the dataset, and thus every write would have some TTL on it.
2. Another way would be through the versioning system, which is not really documented.   The idea is that you keep writing to newer versions over time, and then we provide a functionality to delete older versions.  This way you have the advantage of bulk deletes.

**Comment by velvia** [comment]
Closing as FiloDB has pivoted to an in-memory time series DB and this code path is not applicable any more.  The TSDB has time-based eviction as a primary supported feature.
