### ISSUE TITLE
Correct shading of Guava

### ISSUE THREAD

**Issue by chernals** [filodb/FiloDB#116]
Following Evan's suggestion I changed `build.sbt` to include these, from now on I did not face any more Guava incompatibility issue.

Does that make sense?

  assemblyShadeRules in assembly := Seq(
    ShadeRule.rename("com.datastax.driver.**" -> "filodb.datastax.driver.@1").inAll,
    ShadeRule.rename("com.google.common.**" -> "filodb.com.google.common.@1").inAll,
    ShadeRule.rename("com.google.guava.**" -> "filodb.com.google.guava.@1").inAll
  ),

**Comment by velvia** [comment]
Yeah I think it’s probably harmless.   I guess this is seen in enough environments.

**Comment by chernals** [comment]
Awesome.

**Comment by velvia** [comment]
Want to put together a quick PR?

**Comment by velvia** [comment]
@chernals thanks again.
