### ISSUE TITLE
Spark 2.0 support

### ISSUE THREAD

**Issue by velvia** [filodb/FiloDB#122]
- Merge this change:  https://github.com/SanthoshPrasad/FiloDB/commit/cf2ab88b059e5b17bc802c274ba61d3cdcef2c95

- Create a spark-1.6.x branch

**Comment by SanthoshPrasad** [comment]
Hi @velvia  thanks for considering my changes , we are currently running FiloDB on EMR with spark 2.0.  Are you planning to add scala 2.11 support as well?

By the way i have done minimalistic changes to just make it work with spark 2.0, please suggest if any extra changes required from my side to make it clean.

FiloDB is extremely fast with point lookups compared to other frameworks we evaluated on spark for doing the same, thank you.

- Santhosh.

**Comment by velvia** [comment]
Santhosh,

Yes there is someone else who wants Spark 2.0 with Scala 2.11 support, and we want it as well, so will be working on it.  
Appreciate your changes, will look at it with imminent release of 0.4.  

Would love to sit down with you and understand your use case some time.

-Evan

**Comment by velvia** [comment]
In addition to @SanthoshPrasad 's changes and Scala 2.11 support, consider the following

- Spark 2.0 DataFrameReader / DataFrameWriter APIs
- Structured Streaming:  DataStreamWriter / streaming sink
- Integrate with SparkSession.read/readStream?
- understand how Datasets and Encoders work.  Switch to Dataset[RowReader] with an Encoder based impl for officially supporting InternalRow?
   Check how spark-avro and other libraries implement datasource for 2.0

**Comment by elppc** [comment]
if you are interested i have a working version with Spark 2.0.1 and Scala 2.11
https://github.com/elppc/FiloDB/commit/7263e5b3a7fd10a58363c7e313e6ddb56a632f25

**Comment by velvia** [comment]
@elppc your changes look fine for the most part …. you interested in submitting a PR?  (please strip the IntelliJ changes though)

**Comment by velvia** [comment]
There is now a new PR from @elppc  #132 which includes Scala 2.11 also.

Also, consider some changes in flight for vectorized Spark column processing:

https://issues.apache.org/jira/browse/SPARK-15687
https://github.com/apache/spark/pull/15219
https://github.com/kiszk/spark/blob/dde7caf0c42d3254675b4de57eaf52f8c40e6298/sql/core/src/main/java/org/apache/spark/sql/execution/vectorized/ColumnVector.java

**Comment by khajavi** [comment]
What is the state of this pull request? any plan for Spark 2.0?

**Comment by elppc** [comment]
Hi, I have updated my PR with remarks from velvia and waiting for the merge. You can use my current branch if really needed.

**Comment by velvia** [comment]
There are a couple of big items to merge first; when they are taken cared of, then this will be merged, most likely to new-storage-format branch.

**Comment by velvia** [comment]
Hey everyone, Spark 2.0 has been merged to master.  :)
