### ISSUE TITLE
FiloDB write problem  ( invalid char between encapsulated token and delimiter)

### ISSUE THREAD

**Issue by ArslanSaleem** [filodb/FiloDB#123]
I am to write the same data in cassandra table but i tried to write that data in filo dataset it prompt following error i dont understand the issue.

ERROR CsvRelation$: Exception while parsing line:
19787,"EB8A",14036,3,"58eb844","5305699","NV",1,"1964-03-23","CRL","ROBN"," ADULT","2015-01-22 00:00:00",0,"1324757","81e3a64119","FM","","","","","","","","",1,50,98,98,"2016-01-22 00:00:00","300 WEST \"A\" STREET  FALLON NV 894062947","0","",3,0,"Woods Alessandra",2015,1,"58066","12200X","","green",0,0,0,"N","AFLAC","","2016-01-23",\N. 

java.io.IOException: (line 1) invalid char between encapsulated token and delimiter

**Comment by velvia** [comment]
I think this is a problem with parsing the CSV itself.  Can you share how you are doing the ingestion, is it with the CLI?  
I highly recommend using Spark and spark-csv instead, though if there is some easy setting we can fix to make the CLI CSV ingestion work, we can do that too.

I suspect it is the \N at the end.

**Comment by ArslanSaleem** [comment]
No actually the issue is with few data that has this format "\"A\"" this kind of information in single column because it does not take \" as quote instead it ends which causes an error. This is my code:

var procedurePerformed = sqlcontext.read.format("com.databricks.spark.csv")
				.schema(schema)
                                .option("header", "false")
				.load(file)
				procedurePerformed.cache()
				procedurePerformed.show()

				procedurePerformed.write.format("filodb.spark").
                                option("dataset", "FLSPARK2").
		                option("row_keys", "id").
				mode(SaveMode.Overwrite).save()

**Comment by velvia** [comment]
Have you tried quoteMode?
https://github.com/databricks/spark-csv <https://github.com/databricks/spark-csv>

Either way this is not a FiloDB problem, but rather a Spark-csv problem, so will probably close it.

**Comment by ArslanSaleem** [comment]
yeah i tried spark_csv its writing in cassandra but not in filodb.

**Comment by velvia** [comment]
Are you sure your code is the same?  If you are using Spark, FilODB does not care what your input format is, it is just ingesting through the DataFrame API.   The difference is that writing to C* you might not need a DataFrame.   To test this, write out a Parquet file from your CSV, which also uses DataFrames.  

The original error is in CsvRelation, which is not even in FiloDB code, but rather in spark-csv.

**Comment by ArslanSaleem** [comment]
option("quoteMode", "MINIMAL") while writing to dataset solved the problem. Thanks
