### ISSUE TITLE
Problem writing ingest data to database

### ISSUE THREAD

**Issue by ArslanSaleem** [filodb/FiloDB#128]
I am using 3 C* cluster while writing data to filodb database my code stucks there

16/11/15 15:15:43 INFO package$: Flush completed on 0 nodes for dataset sparkfl2
16/11/15 15:15:43 INFO FiloRelation: Read schema for dataset sparkfl2 = StructType(StructField(

Alltough it has written some data like i have 4.4 Million records it only has written  2 Million. Any help regarding why it stucks on this log

**Comment by velvia** [comment]
@ArslanSaleem first are you sure your keys are unique?   Second, did you sort your data before writing?

**Comment by ArslanSaleem** [comment]
yeah i have unique keys and data is already in ascending order. My execution actually stops at this log.

**16/11/15 15:15:43 INFO FiloRelation: Read schema for dataset sparkfl2 = StructType(StructField(**

**Comment by ArslanSaleem** [comment]
This is my log file error

16/11/16 16:01:41 INFO RddRowSourceActor: (flspark6_0_13_13) Ingestion is all done
16/11/16 16:02:20 ERROR DatasetCoordinatorActor: Error in reprojection task (filodb.flspark6/0)
filodb.core.StorageEngineException: filodb.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency LOCAL_ONE (1 responses were required but only 0 replica responded, 1 failed)

**Comment by velvia** [comment]
How is your keyspace defined?   This error most likely occurs when you define a keyspace on a real cluster with the default settings.   

If you are using FiloDB to create the keyspaces for you, then you need to drop the keyspaces, modify the config file key filodb.cassandra.keyspace-replication-options to something like this:

"{'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'DC1': '3’}"

Alternatively, you can create the keyspace yourself using cqlsh.

Also, this tells me that the ingestion is all done and then you get the error.

Are you sorting your data by the partition key before you ingest?

-Evan

**Comment by ArslanSaleem** [comment]
Thanks for support. I am using default configurations which is  

**keyspace-replication-options = "{'class': 'SimpleStrategy', 'replication_factor': '1'}**

I think this is the issue let me just check.

**Comment by ArslanSaleem** [comment]
Hi,

I am getting this log in one spark worker. It seems to me filodb configuration issue, is there document regarding filodb cluster configuration.

16/11/17 22:10:03 INFO DatasetCoordinatorActor: MemTable flushing rows: 16016
16/11/17 22:10:11 WARN ReliableDeliverySupervisor: Association with remote system [akka.tcp://filo-spark@127.0.0.1:37918] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://filo-spark@127.0.0.1:37918]] Caused by: [Connection refused: /127.0.0.1:37918]

**Comment by velvia** [comment]
Are you sorting the data while ingesting?

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by velvia** [comment]
Basically FiloDB tries to communicate between driver and workers through an Akka port.  Do you need to open extra ports?  If you have only one executor per node, then you can set filodb.spark.executor.port and filodb.spark.driver.port.

**Comment by velvia** [comment]
@ArslanSaleem did you get a chance to try this again?   will close for now, feel free to reopen it.

**Comment by ArslanSaleem** [comment]
Yeah sorting before writing solved the problem. Thanks Evan Chan

**Comment by velvia** [comment]
BTW I have pushed new code into new-storage-format branch, that automatically routes records during ingestion so you don’t have to sort anymore.    You can also use Kafka with 0.4 codebase to sort.

**Comment by ArslanSaleem** [comment]
Thanks Evan. I definitely take a pull and try.
