### ISSUE TITLE
Filodb scala 2.10 support issue

### ISSUE THREAD

**Issue by ArslanSaleem** [filodb/FiloDB#130]
HI all,
Currently i am working on updating records having more 22 paramters but scala  2.10 does not support case class having more than 22 parameters.
I am actually updating Spark dataframe and then update those  records but to update dataframes i had to use spark map but i case class more 22 params not support in scala 2.10 can you any solution on how to update filodb records using spark.

**Comment by velvia** [comment]
You could always construct a Row manually to create a data frame.  You don't have to create a row from a case class. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by ArslanSaleem** [comment]
But spark-2.0.1 dataframe doesn't have that support. It requires case class but in order to transform i had to convert dataframe to rdd and then apply map and after map i had to reconvert it to dataframe and then update new dataframe to filodb.

**Comment by velvia** [comment]
I tried this in the Spark 2.0.1 shell and it still works.

import org.apache.spark.sql.Row
Row.fromSeq(0 to 100)

You can create a Seq[Any] of any length and create Row instances from it.  Once you have an Iterator[Row] you can convert that to a DataFrame using createDataFrame.

With Spark 2.0, you can instead use a DataSet.

Anyways, @elppc has a fork with 2.11 support, you may want to try that.      I might merge from his branch.

**Comment by velvia** [comment]
@ArslanSaleem going to close... if the above doesn't work (between my suggestions and @elppc 's Scala 2.11/Spark 2.0 patch) feel free to reach out on mailing list.
