### ISSUE TITLE
Clarify project status post-Apple acquisition

### ISSUE THREAD

**Issue by acruise** [filodb/FiloDB#131]
Apple has a track record of buying the companies responsible for interesting open source projects, then taking actions that are not advantageous to whatever open source community existed at the time. Seeing as the primary maintainer of FiloDB is working at Apple now, it would be nice to get some kind of statement/promise that Apple intends to continue developing FiloDB in open source, rather than pouring all their resources into a private fork.

**Comment by velvia** [comment]
If you look at the announcement on the filodb-announce mailing list, you will see the statement of support.  You can also see that we have regularly submitted commits back, even as recently as two weeks ago. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by acruise** [comment]
Thanks Evan!

**Comment by velvia** [comment]
We have also continued to merge community contributions back; see #42 for example.
