### ISSUE TITLE
Partition filter GreaterThan and LessThan is not supported.

### ISSUE THREAD

**Issue by tanpinsiang** [filodb/FiloDB#135]
Range filtering across different partition key is not working on version 0.4 and latest new-storage-format branch.

Example below is the time-series range query in SQL and Dataframe.
```sql
SELECT avg(cpu) as cpu FROM node1 WHERE time > 1474237950001 and time < 1474324350001 
```
> java.lang.IllegalArgumentException: Sorry, filter GreaterThan(time,1474237950001) not supported

```scala
df.filter($"time" < 1474324350001L).count()
```
> java.lang.IllegalArgumentException: Sorry, filter LessThan(time,1474324350001) not supported

I would like to work on this.
Which part of the code is a good starting point for me to read before trying to implement this?

**Comment by velvia** [comment]
Thanks for offering to work on this!   Here are some pointers.

in the spark module:  FiloRelation.scala, function called “filtersToFunc”, is where the translation from Spark filter to underlying FiloDB filter function is done.
in filodb.core.query:  KeyFilter.scala has some code used by FiloRelation/filtersToFunc.  You might need to define new functions for >, <, etc.

It’s relatively contained so not difficult to implement.  I would branch off of new-storage-format.

Thanks!

**Comment by velvia** [comment]
Closing as FiloDB has pivoted to an in-memory time series DB and this code path is not applicable any more.  The new code uses Lucene indexing so this can be easily supported.
