### ISSUE TITLE
Filo full scan freeze

### ISSUE THREAD

**Issue by vgkowski** [filodb/FiloDB#138]
Hi, 
I have made a small benchmark with my netflows dataset and compared filo vs cassandra on some basic queries.
My dataset is 4.5 billions netflow and I am using 80 cores and 430 GB of ram for Spark and Cassandra on a 4 bare metal Mesos cluster.
When running this full scan query 
**select count(*) from flows**
It takes 19 minutes to process on Cassandra. With Filo the job freezes, nothing in the driver or executor log. The cassandra metrics are totally flat (no read).

Here is the result from filo-cli

```
./filo-cli-0.4-SNAPSHOT -Dfilodb.config.file=./filodb-defaults.conf --command analyze --dataset netflows2
ColumnStoreAnalysis
  numSegments: 10000
  numPartitions: 4110
===== # Rows in a segment =====
  Min: 1
  Max: 1198655
  Average: 2452.2833 (10000)
| 00000000: 00004326 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
| 00000010: 00002518 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
| 00000100: 00002453 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
| 00001000: 00000587 XXXXXXXX
| 00005000: 00000023
| 00010000: 00000065
| 00050000: 00000028
===== # Chunks in a segment =====
  Min: 1
  Max: 253
  Average: 2.2936 (10000)
| 00000000: 00009923 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
| 00000005: 00000038
| 00000010: 00000019
| 00000100: 00000020
===== # Segments in a partition =====
  Min: 1
  Max: 4
  Average: 2.4330900243309004 (4110)
| 00000000: 00004110 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

```

**Comment by velvia** [comment]
Hi, can you please attach what logs you have?  And also the commit number/branch of FILO, spark version, Scala version.  Thanks

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by elppc** [comment]
Filo version https://github.com/elppc/FiloDB
Spark version 2.0.1
Scala version 2.11

Log from on executor
[stderr.txt](https://github.com/filodb/FiloDB/files/781445/stderr.txt)
Log from the driver
[zeppelin-interpreter-spark-root-BIGDATA-R730-8.rennes.lab.log.txt](https://github.com/filodb/FiloDB/files/781446/zeppelin-interpreter-spark-root-BIGDATA-R730-8.rennes.lab.log.txt)

**Comment by velvia** [comment]
Closing as FiloDB has pivoted to an in-memory time series DB and this code path is not applicable any more.
