### ISSUE TITLE
FiloDB write format fails for Binary

### ISSUE THREAD

**Issue by PallaviPersistent** [filodb/FiloDB#151]
**Branch, version, commit**

**OS and Environment** 
Red Hat Enterprise Linux Server release 7.2 (Maipo)

**JVM version**
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

**Scala version**
Scala version 2.11.8
**Kafka and Cassandra versions and setup**

**Spark version if used**
Spark version 2.0.0

**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
Spark Standalone

**Actual (wrong) behavior**

scala> parDF.write.format("filodb.spark").option("dataset","parDFNF").option("row_keys","appName").option("partition_keys","epoch").mode(SaveMode.Overwrite).save()
[INFO] [04/08/2018 20:25:47.106] [main] [StatsDExtension(akka://kamon)] Starting the Kamon(StatsD) extension
18/04/08 20:25:49 WARN Cluster: You listed localhost/0:0:0:0:0:0:0:1:9042 in your contact points, but it wasn't found in the control host's system.peers at startup
18/04/08 20:25:50 WARN Cluster: You listed localhost/0:0:0:0:0:0:0:1:9042 in your contact points, but it wasn't found in the control host's system.peers at startup
[Stage 1:>                                                       (0 + 0) / 1000]18/04/08 20:25:52 WARN Cluster: You listed localhost/0:0:0:0:0:0:0:1:9042 in your contact points, but it wasn't found in the control host's system.peers at startup
[Stage 1:>                                                       (0 + 2) / 1000]18/04/08 20:25:52 WARN Cluster: You listed localhost/0:0:0:0:0:0:0:1:9042 in your contact points, but it wasn't found in the control host's system.peers at startup
[Stage 1:==================>                                   (334 + 3) / 1000]18/04/08 20:25:56 ERROR FiloMemTable: Error while scanning Memtable WAL folders:/tmp/filodb/wal/null_filodb.jsontest_0
18/04/08 20:25:56 ERROR FiloMemTable: Error while scanning Memtable WAL folders:/tmp/filodb/wal/null_filodb.gdelt_0
18/04/08 20:25:56 ERROR FiloMemTable: Error while scanning Memtable WAL folders:/tmp/filodb/wal/null_filodb.pallavi_0
java.util.NoSuchElementException: key not found: BinaryType
  at scala.collection.MapLike$class.default(MapLike.scala:228)
  at scala.collection.AbstractMap.default(Map.scala:59)
  at scala.collection.MapLike$class.apply(MapLike.scala:141)
  at scala.collection.AbstractMap.apply(Map.scala:59)
  at filodb.spark.package$$anonfun$dfToFiloColumns$1.apply(package.scala:132)
  at filodb.spark.package$$anonfun$dfToFiloColumns$1.apply(package.scala:131)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at org.apache.spark.sql.types.StructType.foreach(StructType.scala:95)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at org.apache.spark.sql.types.StructType.map(StructType.scala:95)
  at filodb.spark.package$.dfToFiloColumns(package.scala:131)
  at filodb.spark.FiloContext$.createOrUpdateDataset$extension(FiloContext.scala:57)
  at filodb.spark.FiloContext$.saveAsFilo$extension(FiloContext.scala:117)
  at filodb.spark.DefaultSource.createRelation(DefaultSource.scala:63)
  at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:429)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:211)
  ... 48 elided

**Steps to reproduce**
val files=Seq("/root/FiloDB/FiloDB/parquetfile/fragment1522917434336000000.dat","/root/FiloDB/FiloDB/parquetfile/fragment1522917494312000000.dat")

val sqlContext = new org.apache.spark.sql.SQLContext(sc)
val parDF=sqlContext.read.parquet(files:_*)
scala> parDF.printSchema
root
 |-- epoch: long (nullable = true)
 |-- rowNum: long (nullable = true)
 |-- exportMs: long (nullable = true)
 |-- exporterIp: binary (nullable = true)
 |-- pktSeqNum: long (nullable = true)
 |-- flowSeqNum: integer (nullable = true)
 |-- srcIp: binary (nullable = true)
 |-- dstIp: binary (nullable = true)
 |-- protocolId: short (nullable = true)
 |-- srcTos: short (nullable = true)
 |-- dstTos: short (nullable = true)
 |-- srcMask: byte (nullable = true)
 |-- dstMask: byte (nullable = true)
 |-- tcpBits: integer (nullable = true)
 |-- srcPort: integer (nullable = true)
 |-- inIfId: long (nullable = true)
 |-- inIfEntityId: long (nullable = true)
 |-- inIfEnabled: boolean (nullable = true)
 |-- dstPort: integer (nullable = true)
 |-- outIfId: long (nullable = true)
 |-- outIfEntityId: long (nullable = true)
 |-- outIfEnabled: boolean (nullable = true)
 |-- direction: byte (nullable = true)
 |-- inOctets: long (nullable = true)
 |-- outOctets: long (nullable = true)
 |-- inPackets: long (nullable = true)
 |-- outPackets: long (nullable = true)
 |-- nextHopIp: binary (nullable = true)
 |-- bgpSrcAsNum: long (nullable = true)
 |-- bgpDstAsNum: long (nullable = true)
 |-- bgpNextHopIp: binary (nullable = true)
 |-- endMs: long (nullable = true)
 |-- startMs: long (nullable = true)
 |-- appId: binary (nullable = true)
 |-- appName: string (nullable = true)
 |-- srcIpGroup: string (nullable = true)
 |-- dstIpGroup: string (nullable = true)
 |-- policyQosClassificationHierarchy: binary (nullable = true)
 |-- policyQosQueueId: long (nullable = true)
 |-- workerId: integer (nullable = true)
parDF.write.format("filodb.spark").option("dataset","parDFNF").option("row_keys","appName").option("partition_keys","epoch").mode(SaveMode.Overwrite).save()

**Logs**

```
some log
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by velvia** [comment]
Closing as FiloDB has pivoted to an in-memory time series DB and this code path is not applicable any more.
