### ISSUE TITLE
Configured Filodb Failed

### ISSUE THREAD

**Issue by ykwzx4585168** [filodb/FiloDB#153]
**Branch, version, commit**
Filodb-0.4
**OS and Environment**
windows 10
**JVM version**
jdk1.8
**Scala version**

**Kafka and Cassandra versions and setup**
none kafka
cassandra 3.1
**Spark version if used**
spark2.3
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
default
**Actual (wrong) behavior**
I am new to Filodb, so this may be a stupid question, but I am very appreciate if you answer my question
I have already configured the cassandra before, but query performance is not good, so I want to try filodb + cassandra + spark, I am following the Filodb document, but when I run the filo-cli in the window command line, it told me "'filo-cli' is not recognized as an internal or external command, operable program or batch file".
what tools shall i install to run "filo-cli"?

thanks again

**Steps to reproduce**

**Logs**

```
some log
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by velvia** [comment]
The new version on develop branch has a `./filo-cli.sh` script in the root folder to help you run it.   However it is also very different.
