### ISSUE TITLE
Explore direct, non-networked reads for faster I/O

### ISSUE THREAD

**Issue by milliondreams** [filodb/FiloDB#39]
We should look into storing the local FiloDB data directly on Disk (and not in Cassandra). Thhis way we will be able to bypass cassandra (and all the network overhead and serde)  while querying.

This will also remove the hard-link between FiloDB and cassandra and FiloDB can then sit behind any data distribution framework or distributed database engine without needing C*.

It will also pave the way for us to harness the memory-mapped reading (one of the core selling points for FlatBuffers) and off-heap processing and possibly SIMD and GPGPU support. 

And finally, it will be good step towards native Tungsten bindings.

**Comment by rstrickland** [comment]
I see the rationale, but would caution that building out Cassandra-like functionality (including multi-DC replication) is non-trivial.  Personally it seems to make more sense to use a proven storage layer than to try to reinvent that.  What I could see would be a pluggable storage layer, but then you risk reducing to the lowest common denominator.  I'll also add that I probably wouldn't use FiloDB if it meant having to run additional infrastructure outside of our existing Cassandra-Spark installation.  The drop-in library aspect makes it more appealing and easier to adopt IMHO.

**Comment by velvia** [comment]
@rstrickland the ColumnStore API is pluggable - in fact there are two implementations, the C* one and an in-memory one.    

@milliondreams so a non-C* columnStore, and reading directly from disk, and off-heap are all separate issues.  How about we change this ticket to be for direct (i.e. no-network) reads from disk, to enable faster read performance?  That's closer goal than a non-C* columnstore.  We could, for example, directly parse SSTables - though I think we have a ways to go before this becomes a performance bottleneck.   This allows us to reuse C* infrastructure but still read quickly.

**Comment by velvia** [comment]
Let's close this for now.
