### ISSUE TITLE
Upgrade to SBT 1.x

### ISSUE THREAD

**Issue by velvia** [filodb/FiloDB#458]
This might be nontrivial due to our use of project/Filo{Build,Settings}.scala, but will be worth it for the new features It brings.  Perfect for a Scala dev who's new to the project.

**Branch, version, commit**

**OS and Environment**

**JVM version**

**Scala version**

**Kafka and Cassandra versions and setup**

**Spark version if used**

**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)

**Actual (wrong) behavior**

**Steps to reproduce**

**Logs**

```
some log
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by xingyif** [comment]
In pr: #503

**Comment by broneill** [comment]
Merged.
