### ISSUE TITLE
Investigate Apache Calcite integration

### ISSUE THREAD

**Issue by velvia** [filodb/FiloDB#64]
Apache Calcite has what seems like more robust ANSI SQL support and query optimization than Spark.  It has Spark integration.  Investigate using that as a JDBC driver/server and either using filodb.spark with spark adapter, or writing a FiloDB direct adapter.

**Comment by velvia** [comment]
Spoke to the Calcite guy.  Spark support is third party.   Still might be worth investigating for more robust SQL support.

Also see Trafodion:
https://trafodion.apache.org

Has a lot of pretty awesome query optimizations, is based on SQL Server / "Cascades" latest gen query optimization

**Comment by elppc** [comment]
What about Spark 2.0 ? It supports now ANSI SQL and can run TPC-DS which means for me the SQL maturity is quit good ?

**Comment by velvia** [comment]
It's getting better for sure.  Perhaps after Spark 2.0 we could close this

**Comment by velvia** [comment]
Let's close this for now.
