### ISSUE TITLE
FiloDB Compaction

### ISSUE THREAD

**Issue by velvia** [filodb/FiloDB#76]
1. On disk compaction of fragmented segments into more unified segments
2. Ingestion-time compaction of fragmented segments into more complete ones

The second one is perhaps 2-3 days worth of work, and would be valuable especially for InMemoryColumnStore.

**Comment by velvia** [comment]
Number of chunks in a partition can impact the performance of reads. Depending on partition strategy and the frequency of data inserted into partition, it is possible that we might end up with fragmented chunks over time.

Ex: Table is partition by transaction month and transactions are loaded every day.

Please document tuning options to manage chunks post insertion.

**Comment by velvia** [comment]
Going to take a different approach

**Comment by angelok1** [comment]
One approach to this could be to run a spark job to compact (by reading the data, then writing it back). Is there a reliable method to compute a partition that needs compaction? I thought about exposing some of the stats in Analyzer to Spark, but I'm still not clear on what the formula would be.

**Comment by velvia** [comment]
@angelok1 thanks, the code base has changed a huge amount so I don't remember anymore.  Right now FiloDB is very memory based so likely would try to do in-memory (mostly) based compaction to reduce I/O. Otherwise the impact of a read-modify-write cycle to C* would be huge and destroy SLAs for queries.   Feel free to get in touch about where the project currently is.

**Comment by angelok1** [comment]
Sounds good. Would it make sense to communicate offline?

**Comment by velvia** [comment]
Sure thing.
