### ISSUE TITLE
Ability to restart ingestion with different schema

### ISSUE THREAD

**Issue by java8964** [filodb/FiloDB#86]
Hi, I am testing the update existing data in FiloDB. I understand there is version concept in it, but by default, every push will overwrite the version 0 by default, so I expect the new data will OverWrite the old data.

I am testing this on one Linux box, running DSE 4.8.5 (with C\* 2.1.13) and Spark 1.5.2 with FiloDB 0.2.1-master trunk. I am generating 1M emails, using the first 2 characters as the partition key, domain of the email as segment key, and unique email address as the row key.

1) Starting Spark 1.5.2, disabling Tungsten sort, and running it as local
[yzhang@yzhang-linux data]$ ~/spark/bin/spark-shell --conf spark.sql.tungsten.enabled=false --conf spark.sql.shuffle.partitions=1 --jars /home/yzhang/source/FiloDB/spark/target/scala-2.10/filodb-spark-assembly-0.2.1-SNAPSHOT.jar,/home/yzhang/lib/commons-csv-1.2.jar,/home/yzhang/lib/spark-csv_2.10-1.4.0.jar --driver-memory 3G --master local[2]
2) Load the CSV file, and save them into the FiloDB
scala>val csvDF = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/home/yzhang/data/poc2_1m.csv")
val df = csvDF.withColumn("PartId", substring($"Email", 0, 2)).sort($"PartId").drop("PartId")
df: org.apache.spark.sql.DataFrame = [Email: string, Domain: string, GlobalStop: int, RestrictedAddress: int, RestrictedDomain: int, RoleAddress: int, Active: int]
scala> df.write.format("filodb.spark").option("dataset", "poc2").option("row_keys", "Email").option("segment_key", "Domain").option("partition_keys", ":stringPrefix Email 2").mode(SaveMode.Overwrite).save()
3) The data saved without any problem, and I can query it.
scala> val poc2 = sqlContext.read.format("filodb.spark").option("dataset", "poc2").load()
poc2: org.apache.spark.sql.DataFrame = [RestrictedDomain: int, RestrictedAddress: int, Email: string, GlobalStop: int, RoleAddress: int, Domain: string, Active: int]
scala> poc2.count
res1: Long = 1000000
scala> poc2.registerTempTable("poc2")
scala> sqlContext.sql("select count(*) from poc2 where GlobalStop = 1").show()
+------+
|   _c0|
+------+
|500034|
+------+

4) Now I use the same data, but I overwrite the GlobalStop field all to "1", and tried to save again:
scala>val csvDF = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/home/yzhang/data/poc2_1m.csv")
scala> def udfSetOne=udf((input:Int) => 1)
scala> val updatedDF = csvDF.withColumn("newGlobalStop", udfSetOne(csvDF("GlobalStop"))).drop("GlobalStop").withColumnRenamed("newGlobalStop","GlobalStop").withColumn("PartId", substring($"Email", 0, 2)).sort($"PartId").drop("PartId")
scala> updatedDF.printSchema
root
 |-- Email: string (nullable = true)
 |-- Domain: string (nullable = true)
 |-- RestrictedAddress: integer (nullable = true)
 |-- RestrictedDomain: integer (nullable = true)
 |-- RoleAddress: integer (nullable = true)
 |-- Active: integer (nullable = true)
 |-- GlobalStop: integer (nullable = true)

So what I did is to read the same csv file again, but this time, I use a UDF to create a new column named "newGlobalStop" with value to 1, drop old "globalStop", and rename "newGlobalStop" to "globalStop"
So I created a new Dateframe, same schema as before, but with "globalStop" column with value as 1 ONLY.

scala> updatedDF.registerTempTable("df")
scala> sqlContext.sql("select count(*) from df where GlobalStop = 1").show()
+-------+
|    _c0|
+-------+
|1000000|
+-------+

The above proves the new DF with only 1 as GlobalStop value

5) Now write them to FiloDB again, to the same dataset:
scala> updatedDF.write.format("filodb.spark").option("dataset", "poc2").option("row_keys", "Email").option("segment_key", "Domain").option("partition_keys", ":stringPrefix Email 2").mode(SaveMode.Overwrite).save()

6) So far, I didn't get any error, so I use a new dataset overwrite the old one, with 1 as only value in one field.

7) But when I query "poc2" dataset again from FiloDB, I didn't get the new value as I expected:
scala> val poc2 = sqlContext.read.format("filodb.spark").option("dataset", "poc2").load()
poc2: org.apache.spark.sql.DataFrame = [RestrictedDomain: int, RestrictedAddress: int, Email: string, GlobalStop: int, RoleAddress: int, Domain: string, Active: int]
scala> poc2.registerTempTable("poc2")
scala> sqlContext.sql("select count(*) from poc2 where GlobalStop = 1").show()
+------+
|   _c0|
+------+
|500034|
+------+

It looks like my overwrite of 2nd time just being ignored. 

Did I do something wrong, or I misunderstand how the data can be updated in FiloDB?

Thanks

Yong

**Comment by java8964** [comment]
ok. I think I kind of understand the problem now.

The issue is that when the Dataframe sent to FiloDB, even DataFrame has the schema, but FiloDB is use the columns location, instead of the column name in the schema to decide what value should be applied on what columns.

This problem comes out I want to write a test problem to test the data update, but since Spark DataFrame is immutable, instead of generating the updated csv file, I want to change DataFrame value in the memory, by dropping the old column, and rename the column, then I found out FiloDB won't update the correct value based on the name of the column in DataFrame, but based on the location.

This problem existed in in-memory test, so it has nothing to do with C*. I demo the problem using one line of row data:

Email,Domain,GlobalStop,RestrictedAddress,RestrictedDomain,RoleAddress,Active
w7h1@yahoo.com,yahoo.com,0,0,0,0,0

The above is one row of csv file, with the header. All the value are 0.

Load the data into filoDB:
val csvDF = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/home/yzhang/data/emails_1.csv")

df.write.format("filodb.spark").option("dataset", "poc1").option("row_keys", "Email").option("segment_key", "Domain").option("partition_keys", ":stringPrefix Email 2").mode(SaveMode.Overwrite).save()

Then the data looks good:
scala> val poc1 = sqlContext.read.format("filodb.spark").option("dataset", "poc1").load()
poc1: org.apache.spark.sql.DataFrame = [RestrictedDomain: int, RestrictedAddress: int, Email: string, GlobalStop: int, RoleAddress: int, Domain: string, Active: int]

scala> poc1.show
+----------------+-----------------+--------------+----------+-----------+---------+------+
|RestrictedDomain|RestrictedAddress|         Email|GlobalStop|RoleAddress|   Domain|Active|
+----------------+-----------------+--------------+----------+-----------+---------+------+
|               0|                0|w7h1@yahoo.com|         0|          0|yahoo.com|     0|
+----------------+-----------------+--------------+----------+-----------+---------+------+

Now after this, if I generate a new Dataframe, with same columns, but different order, and one updated value, see below:

scala> df.show
+--------------+---------+-----------------+----------------+-----------+------+----------+
|         Email|   Domain|RestrictedAddress|RestrictedDomain|RoleAddress|Active|GlobalStop|
+--------------+---------+-----------------+----------------+-----------+------+----------+
|w7h1@yahoo.com|yahoo.com|                0|               0|          0|     0|         1|
+--------------+---------+-----------------+----------------+-----------+------+----------+

You can see it is the same row, but column "GlobalStop" switched from location 3 to 7, and with a updated value 1, instead of originally 0, and now we tried to save this Dateframe:

scala> df.write.format("filodb.spark").option("dataset", "poc1").option("row_keys", "Email").option("segment_key", "Domain").option("partition_keys", ":stringPrefix Email 2").mode(SaveMode.Overwrite).save()

scala> val poc1 = sqlContext.read.format("filodb.spark").option("dataset", "poc1").load()
poc1: org.apache.spark.sql.DataFrame = [RestrictedDomain: int, RestrictedAddress: int, Email: string, GlobalStop: int, RoleAddress: int, Domain: string, Active: int]

scala> poc1.show
16/04/07 20:58:43 WARN RowReaderSegment: empty chunk detected!  chunkId=0 in SegmentInfo(w7,yahoo.com)
+----------------+-----------------+--------------+----------+-----------+---------+------+
|RestrictedDomain|RestrictedAddress|         Email|GlobalStop|RoleAddress|   Domain|Active|
+----------------+-----------------+--------------+----------+-----------+---------+------+
|               0|                0|w7h1@yahoo.com|         0|          0|yahoo.com|     1|
+----------------+-----------------+--------------+----------+-----------+---------+------+

After the data saved in FiloDB, it is clear that wrong column "Active" had been updated, instead of "GlobalStop", and we can see that the value 1 is being written on the 7th column. So FiloDB only apply the data based on the location of the columns in the following ingestion, instead of depending the schema given in the Dataframe.

Thanks

Yong

**Comment by velvia** [comment]
@java8964 many thanks.  I'll add a test for this and try to fix it.  It's a great catch, thanks!
Hopefully today.

**Comment by velvia** [comment]
By the way, I’ve looked more into this issue and understand exactly why it is happening now.  The problem is that FiloDB ingestion right now is fixed to one schema - the first schema/Dataframe you ingest for a dataset.    To document the flow so I remember too:

DataFrame.write calls FiloContext.insertAsFilo(), which in turn spins up an RddRowSourceActor, which is a RowSource.  
This in turn sends SetupIngestion message to NodeCoordinatorActor.  The problem is that the ingestion is based on a fixed schema right now, and subsequent data frame write’s will send SetupIngestions, but get ignored because the ingestion is “already setup” for a particular schema.

The short term fix would be to drop the current ingestion (making sure data is flushed), then set it up for the new updated schema.  The longer term fix would be to allow for dynamically changing schemas, but has to be thought about a bit more.

**Comment by java8964** [comment]
Hi, Evan:

I understand this is current a limitation of fixed schema requirement. I read some part code of FiloDB, is this due to underline format of org.velvia.filo only store the value, and lost the corresponding schema? Will append new columns be fine? Use you own storage format, instead of Parquet is tough, as you have to do everything again, instead of reusing the existing "schema evolution" support already from other library.

**Comment by velvia** [comment]
Yong,

No it’s not a matter of using our own format.  Appending new columns right now should be OK, but only if you restart the Spark app.  Actually, that is the trick - if you are willing to restart the Spark app, the state is reset and you can use a new schema.

-Evan

**Comment by java8964** [comment]
I confirm that the single line bug won't be reproduced if I shutdown and restart the spark app.
This is good enough for us, as our write path right now will be batch ingestion, so every ingestion should be a new spark app.

Now, I will continue my writing test, since I know I have to start a new Spark app every time, if schema changes. I did see rows lost while ingesting tons of millions rows in one batch. Based on your experience, this could be ONLY related to the part FiloDB writing to C*, or also to memory store? Use memory store is convenient for testing, but maybe not easy to reproduce the problem.

Yong

**Comment by velvia** [comment]
I don’t think it’s C* specific.  I suspect rows can be lost because we are improperly flushing the memtable for a cluster, but will add metrics to debug and verify this.

**Comment by velvia** [comment]
How about we leave this ticket for the original bug - updating data?   We can start separate ticket for the # rows mismatch.  Or note on #90.

**Comment by velvia** [comment]
There should be an ability to start a new ingestion in the same Spark app with a different schema than original without having to restart Spark app. 

Not sure if this will make 0.3 yet.
